### PR TITLE
Color rows of the table based on completion status

### PR DESCRIPTION
**Pull request by satyarth**
Allows you to gauge completion status at a glance. Depends on `started` and `completed` json fields, same as the counter on the front page.

Since this is my first experience with react, I don't want to merge it myself. @okpatil4u or @bogas04, could you take a look and merge if it's ok?

### CODE REVIEW

**Comment by satyarth** [comment]
Here's what it looks like: preview

**Comment by okpatil4u** [comment]
@satyarth looks good.

**Comment by greyhound291** [comment]
Instead of coloring a the text, can we colour a block on the left side of the category or title?

**Comment by okpatil4u** [comment]
We can add tags based on status

**Pull request merged**
